apiVersion: v1
kind: ConfigMap
metadata:
  name: dora-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dora.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "dora.doraConfig" . | nindent 4 }}
