apiVersion: v1
kind: Secret
metadata:
  name: dora-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dora.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  POSTGRES_DB: {{ .Values.db.name }}
  DATABASE_URL: {{ include "dora.databaseUrl" . | quote }}
